### ISSUE TITLE
Video in the ReadMe link doesn't work

### ISSUE THREAD

**Issue by ianceicys** [prprprus/softest#2]
Just tried accessing the video and it doesn't work. 
https://vimeo.com/user101898119/review/354273223/1040ac0c06

![image](https://user-images.githubusercontent.com/3976990/63193771-4cc41380-c03c-11e9-84f6-e656464f22a0.png)

**Comment by prprprus** [comment]
Hi, @ianceicys 

Thank you for your reminder, it should be OK now.
