### ISSUE TITLE
这个是什么错误呢

### ISSUE THREAD

**Issue by Pain-and-Love** [prprprus/softest#3]
![](https://i.loli.net/2019/08/23/UQa7cGFYx1oAuqr.png)

**Comment by Pain-and-Love** [comment]
这个问题解决了。 但是我在点击了那个record按钮之后，并没有出现 puppeeter 的初始化代码。。也没有后续的操作相关的代码

**Comment by prprprus** [comment]
权限问题吧😂

**Comment by Pain-and-Love** [comment]
> 权限问题吧😂

确实。。 不能直接在 desktop 里创建文件。
